### ISSUE TITLE
Audio from VTT files

### ISSUE THREAD

**Issue by antonioberetini** [ealmuneyeer/CognitiveServicesGenerateVTT#2]
Hey any chance you have a solution to generate audio with cognitive services text to speech using VTT as an input?

**Comment by ealmuneyeer** [comment]
Hi there, I do not have anything readymade, and by looking at the cognitive services [Speech service documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/overview) it seems not supported, and the best shot is to convert the VTT file into [SSML](https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/speech-synthesis-markup?tabs=csharp)

**Comment by ealmuneyeer** [comment]
Closing issue as it's not related directly to this application.
